// Mocks generated by Mockito 5.4.6 from annotations
// in trivia_app/test/features/random_pokemon/presentation/bloc/pokemon_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trivia_app/core/error/failure.dart' as _i6;
import 'package:trivia_app/core/util/input_converter.dart' as _i10;
import 'package:trivia_app/core/util/params.dart' as _i8;
import 'package:trivia_app/core/util/random_number_generator.dart' as _i11;
import 'package:trivia_app/features/random_pokemon/domain/entities/pokemon.dart'
    as _i7;
import 'package:trivia_app/features/random_pokemon/domain/repositories/pokemon_repository.dart'
    as _i2;
import 'package:trivia_app/features/random_pokemon/domain/usecases/get_concrete_pokemon_by_id.dart'
    as _i4;
import 'package:trivia_app/features/random_pokemon/domain/usecases/get_random_pokemon_id.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonRepository_0 extends _i1.SmartFake
    implements _i2.PokemonRepository {
  _FakePokemonRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetConcretePokemonById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConcretePokemonById extends _i1.Mock
    implements _i4.GetConcretePokemonById {
  MockGetConcretePokemonById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePokemonRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PokemonRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Pokemon>> call(_i8.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Pokemon>>.value(
            _FakeEither_1<_i6.Failure, _i7.Pokemon>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Pokemon>>);
}

/// A class which mocks [GetRandomPokemonId].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomPokemonId extends _i1.Mock
    implements _i9.GetRandomPokemonId {
  MockGetRandomPokemonId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePokemonRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PokemonRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Pokemon>> call(_i8.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Pokemon>>.value(
            _FakeEither_1<_i6.Failure, _i7.Pokemon>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Pokemon>>);
}

/// A class which mocks [InputConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputConverter extends _i1.Mock implements _i10.InputConverter {
  MockInputConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Either<_i6.Failure, int> stringToUnsignedInteger(String? str) =>
      (super.noSuchMethod(
        Invocation.method(
          #stringToUnsignedInteger,
          [str],
        ),
        returnValue: _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #stringToUnsignedInteger,
            [str],
          ),
        ),
      ) as _i3.Either<_i6.Failure, int>);
}

/// A class which mocks [RandomNumberGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomNumberGenerator extends _i1.Mock
    implements _i11.RandomNumberGenerator {
  MockRandomNumberGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: 0,
      ) as int);
}
