// Mocks generated by Mockito 5.4.6 from annotations
// in trivia_app/test/features/random_pokemon/data/repositories/pokemon_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:trivia_app/core/network/network_info.dart' as _i6;
import 'package:trivia_app/features/random_pokemon/data/datasources/pokemon_local_data_source.dart'
    as _i5;
import 'package:trivia_app/features/random_pokemon/data/datasources/pokemon_remote_data_source.dart'
    as _i3;
import 'package:trivia_app/features/random_pokemon/data/models/pokemon_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonModel_0 extends _i1.SmartFake implements _i2.PokemonModel {
  _FakePokemonModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRemoteDataSource extends _i1.Mock
    implements _i3.PokemonRemoteDataSource {
  MockPokemonRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PokemonModel> getConcretePokemonById(int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConcretePokemonById,
          [number],
        ),
        returnValue: _i4.Future<_i2.PokemonModel>.value(_FakePokemonModel_0(
          this,
          Invocation.method(
            #getConcretePokemonById,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.PokemonModel>);

  @override
  _i4.Future<_i2.PokemonModel> getRandomPokemonId(int? randomnumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomPokemonId,
          [randomnumber],
        ),
        returnValue: _i4.Future<_i2.PokemonModel>.value(_FakePokemonModel_0(
          this,
          Invocation.method(
            #getRandomPokemonId,
            [randomnumber],
          ),
        )),
      ) as _i4.Future<_i2.PokemonModel>);
}

/// A class which mocks [PokemonLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonLocalDataSource extends _i1.Mock
    implements _i5.PokemonLocalDataSource {
  MockPokemonLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PokemonModel> getLastRandomPokemon() => (super.noSuchMethod(
        Invocation.method(
          #getLastRandomPokemon,
          [],
        ),
        returnValue: _i4.Future<_i2.PokemonModel>.value(_FakePokemonModel_0(
          this,
          Invocation.method(
            #getLastRandomPokemon,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PokemonModel>);

  @override
  _i4.Future<void> cacheRandomPokemon(_i2.PokemonModel? pokemonToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheRandomPokemon,
          [pokemonToCache],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
